### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Chaphasilor** [Chaphasilor/odcrawler-frontend#35]
The readme should include some more relevant info and look a bit nicer :)

**Comment by MCOfficer** [comment]
For more style points, there are badges for our status page: http://shields.io/category/monitoring

**Comment by Chaphasilor** [comment]
![image](https://user-images.githubusercontent.com/18015147/102551072-3100cf80-40bf-11eb-927b-cf571e75ddd3.png)
mind sharing those api keys for all of our services?

**Comment by Chaphasilor** [comment]
Some endpoints for various stats would also be cool. Like one that returns the amount of indexed links, one for the amount of indexed ODs, etc.

We could use that with dynamic Shields :D

**Comment by MCOfficer** [comment]
Website: m786605489-b418dd2b30029ffd44f60f5c

Elasticsearch: m786605474-aefb8b00783d9151d10f204e

Search Server: m786605477-0d07f387d5ad4a952c0859e2

Discovery Server: m786605483-e2e9ac70943fe44fc85b8d64

**Comment by MCOfficer** [comment]
You can create dynamic badges from the existing endpoints, f.e.

```
https://img.shields.io/badge/dynamic/json?label=Total%20Links&query=total_links&url=https%3A%2F%2Fdiscovery.odcrawler.xyz%2Fstats.json
```
<img src="https://img.shields.io/badge/dynamic/json?label=Total%20Links&query=total_links&url=https%3A%2F%2Fdiscovery.odcrawler.xyz%2Fstats.json"></img>

```
https://img.shields.io/badge/dynamic/json?label=Indexed&query=_all.primaries.docs.count&url=https%3A%2F%2Fsearch.odcrawler.xyz%2Felastic%2Flinks%2F_stats
```
<img src="https://img.shields.io/badge/dynamic/json?label=Indexed&query=_all.primaries.docs.count&url=https%3A%2F%2Fsearch.odcrawler.xyz%2Felastic%2Flinks%2F_stats"></img>

The URL generator is about halfway down the page on https://shields.io/.

**Comment by Chaphasilor** [comment]
> You can create dynamic badges from the existing endpoints, f.e.
> 
> ```
> https://img.shields.io/badge/dynamic/json?label=Total%20Links&query=total_links&url=https%3A%2F%2Fdiscovery.odcrawler.xyz%2Fstats.json
> ```

uhh, I didn't saw the query part! I was wondering if something like that was possible \^\^
