### ISSUE TITLE
Suggestion: When using Copy Link, copy the link with substitutions for wget compatibility

### ISSUE THREAD

**Issue by Emstar** [Chaphasilor/odcrawler-frontend#4]
When I use Copy Link on an URL with spaces, the raw URL text is copied. For better compatibility with tools like wget, it would be cool if necessary substitutions were made, like " " to "%20". 

(I think such a translation would also be compatible with browser URLs--they just do it for you when you try to navigate using raw text.)

**Comment by Chaphasilor** [comment]
Interesting idea! I'll see what I can do :)

**Comment by Emstar** [comment]
I do not know all the rules for properly escaping whitespace, etc. When I want to use wget, I use a [wget GUI](https://www.astatix.com/tools/winwget.php) front-end which handles the conversion for me. It is super handy. (The GUI _itself_ is actually crappy and crashes all the time, so I use its command line in the normal CLI wget... but having that link translation done is a huge time saver.)

**Comment by Chaphasilor** [comment]
JavaScript's `encodeURI()` function is exactly for that. I've just pushed the changes to the dev branch (as you can see above your comment) and you might already see the changes on [the site](beta.odcrawler.xyz)!

(I just set up A/B testing so I can't guarantee you'll see them...)

**Comment by Emstar** [comment]
Super cool!
