### ISSUE TITLE
URLs copied to clipboard don't always match the original URL

### ISSUE THREAD

**Issue by Chaphasilor** [Chaphasilor/odcrawler-frontend#44]
Example:

Original URL: `http://103.91.144.230/ftpdata/Movies/Hollywood/2013/New%20Added/The%20Hunger%20Games%20Catching%20Fire%20%282013%29/The.Hunger.Games.Catching.Fire.2013.1080p.BluRay.x264.YIFY.mp4`  
When copied to clipboard: `http://103.91.144.230/ftpdata/Movies/Hollywood/2013/New%20Added/The%20Hunger%20Games%20Catching%20Fire%20%25282013%2529/The.Hunger.Games.Catching.Fire.2013.1080p.BluRay.x264.YIFY.mp4`

Notice the `%28` and `%29` vs `%2528` and `%2529`.

Maybe this is related to brackets around numbers?  
(It also seems like some servers can handle it, not confirmed though!)

**Comment by MCOfficer** [comment]
It's somehow reencoding it: `%28` is `%`, so `%2528` literally the URLEncoded version of `%25`

**Comment by Chaphasilor** [comment]
> It's somehow reencoding it: `%25` is `%`, so `%2528` literally the URLEncoded version of `%25`

Thanks for pointing that out! I guess in that case the original URL might be already encoded, resulting in the double encoding...

If that really is the case, decoding it and then re-encoding it should do the trick :D

**Comment by Chaphasilor** [comment]
![Screenshot_20210117-005317.png](https://user-images.githubusercontent.com/18015147/104827492-7b13d700-585e-11eb-954a-807b679aa719.png)

Bingo!
