### ISSUE TITLE
Suggestion: put some search hints on the front page

### ISSUE THREAD

**Issue by Emstar** [Chaphasilor/odcrawler-frontend#6]
I see a link to the search API but a quick look didn't tell me what kind of search syntax is allowed. Can we use wild cards? Quotes? Search by file extension? A few words about that would help a lot.

**Comment by Chaphasilor** [comment]
I'm honestly not sure myself...
I think it's just free-text search without any special characters, but maybe @MCOfficer knows more about it?

**Comment by MCOfficer** [comment]
/meili/indexes/links/search is a direct proxy of Meilisearch's search route. I can't tell you more than is in their docs: https://docs.meilisearch.com/references/search.html

**Comment by Chaphasilor** [comment]
Okay, seems like there are some filtering options, but nothing that would be of much use to us.

The only use-case I found would be filtering results based on file size, but given that the backend will now stop returning file sizes for performance reasons, that isn't possible either.

No wild cards for you, sorry :/

**Comment by MCOfficer** [comment]
One more remark: I posted a database dump [here](https://www.reddit.com/r/opendirectories/comments/iujn11/are_there_any_decent_online_od_databases_for/g5vc7v2?utm_source=share&utm_medium=web2x&context=3), you download that and regex-search it (irecommend `ripgrep`).

Since this is a dump of the discovery backend, not the search indexing, it includes 49M links that haven't been indexed by the engine yet.

**Comment by Emstar** [comment]
Thanks for the info guys! I know there is only so much you can do. 

I will keep looking at the documentation and if I figure out anything that helps searchers, I will let you know. This search API is not bad, just a little unconventional. 

This section on filtering in the query seems promising. 

https://docs.meilisearch.com/guides/advanced_guides/filtering.html

Note they use examples like searching for text in the "title" field. If the index defined fields for "path" and "filename" then you could focus your search pretty well. 

I checked the db dump and it's naked URLs. So, it does seem like an index modification would be needed to allow searching for stuff in just the filename. (Crossing paths with that other suggestion I filed.)

It might be possible to use some of their search syntax now. Look at this example of theirs, which searches the "title" field. 

_title = Scream OR title = "The Avengers"_

In the existing index, what is the API's field name of the one field that holds the URL? If I had that I could test to see if syntax like the above works, which would be sweet.

**Comment by MCOfficer** [comment]
for the time being, you can regex the filenames: `/your filename.txt$`

**Comment by Chaphasilor** [comment]
> In the existing index, what is the API's field name of the one field that holds the URL? 

it's simply `url`. There's also `id` and `size`, with the latter soon being removed :)

**Comment by Chaphasilor** [comment]
Without #7, I don*t think this is needed yet. I'll leave it open though, so that I'll remember it later 😅

**Comment by Emstar** [comment]
I tried using some of the search syntax in their docs, but I don't think the field name is exposed, or something. For example, I tried just copying a search result link for some random MP3, and then tried to make a search that returned that file only, like:

url = "http://some.domain.com/path/file.mp3"

That didn't return anything at all. I think it is barfing on the forward slashes, or something like that... Searching for a partial path like foo/bar returns nothing even when I know there should be a hit. 

Anyway, I don't think there is any magical help text that can get the API to do tricks. Looks like "must match all words" is all it does.

**Comment by Chaphasilor** [comment]
@Emstar I think the search by field can only be done programatically, i.e. it has to be specified outside the query itself? I'll have to look into it again...

**Comment by Chaphasilor** [comment]
So yeah, filters go into a separate query parameter:

from Meili docs:
```curl
curl 'http://localhost:7700/indexes/movies/search' \
--data '{ "q": "Avengers", "filters": "release_date > 795484800" }'
```

I'll see if I can design some kind of 'advanced search' that let's you apply these filters and give an overview over the available fields and operators!

**Comment by Emstar** [comment]
Makes sense, it was too much to hope for that the raw query would work that way. Advanced search would be a great addition. 

After using the beta more and trying to really use it to find specific things of interest, I do still think that a way to restrict search to the file name would be the most useful addition. If you did add an advanced search, then you'd have the framework in place... then the index could be updated to include the filename as a field someday. 

Anyway thanks again for all the work on this!

**Comment by Chaphasilor** [comment]
@MCOfficer is currently re-indexing all links (at least those who still work), with a separate field for the filename. Once that is done (end of the weekend most likely), I'll add a checkbox to 'Only search filename'.

I've looked into the docs a bit more and as of now there seems to be now way to have search match a sub-string exactly. I also don't know if any more characters will be converted to spaces like `.`

I will keep this issue up-to-date :)

**Comment by Emstar** [comment]
Thanks @Chaphasilor and @MCOfficer, great news.

**Comment by Chaphasilor** [comment]
So we now have separate access to the filename on 4M+ links, I'll add filename-only search tomorrow :)

**Comment by Emstar** [comment]
Awesome @Chaphasilor ! 

I checked it out a couple of times today but it's saying: 

_Couldn't load search results :/_

I'll check back later and maybe file more irritating feedback. ;)

**Comment by MCOfficer** [comment]
Yeah, the search engine crashed overnight. I added a fallback that will at least restart the engine in case shit hits the fan. We're now at 5M links and counting!

**Comment by Chaphasilor** [comment]
Didn't get around to this today, hopefully tomorrow :/
